Add luke to members
mphowardlab/mphowardlab.github.io pull request #43
Opened 2024-05-21 20:02 UTC by Cravey0053

Adds Luke Cravey to People tab. Includes profile text and profile image

2024-05-22 14:33 UTC, mphoward requested changes
Thanks Luke! This looks great. Can you please merge `main` into this branch, and then apply the change below? I will merge after that.

2024-05-22 14:33 UTC, mphoward commented on _members/cravey-luke.md
> +role: undergrad
We changed the name of this role on the `main` branch, so this should become:
```suggestion
role: undergrad-student
```

2024-05-28 13:15 UTC, Cravey0053 commented
> Thanks Luke! This looks great. Can you please merge `main` into this branch, and then apply the change below? I will merge after that.

Done! Should be good to go.

2024-05-28 14:50 UTC, mphoward approved these changes
All good, thank you!

2024-05-28 14:51 UTC, merged